### ISSUE TITLE
今日新增魯文無法顯示

### ISSUE THREAD

**Issue by yuessir** [huayinthon/til#1]
今日新增魯文無法顯示<2015-11-03-巨型網站簡單說>
步驟
1.pull 到目前最新檔案
2.commit push
http://sdn.huayinthon.xyz/blog/ 無法順利顯示請問我是在哪個步驟環節操作錯誤呢?謝謝~~

**Comment by ghost** [comment]
因為 travisci 失去作用了，所以網頁不會傳上前端

##

**Comment by yuessir** [comment]
了解是我上傳的過程中把檔案弄壞了

**Comment by ghost** [comment]
應該可以上 travisci 上看，之前就爛掉了

##
